@extends('layouts.admin')

@section('title', 'Creer un tag')
@section('page-title', 'Nouveau tag')
@section('page-description', 'Creation d\'un nouveau tag')

@section('content')
<div class="container-fluid">
    <form method="POST" action="{{ route('admin.tags.store') }}">
        @include('admin.tags.partials.form', [
            'submitLabel' => 'Creer le tag'
        ])
    </form>
</div>
@endsection

@push('styles')
<style>






.bg-gradient-warning {
    background: linear-gradient(135deg, #f59e0b 0%, #10b981 100%);
}
</style>
@endpush

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Auto-generation du slug A partir du nom
    const nameInput = document.getElementById('name');
    const slugInput = document.getElementById('slug');
    
    nameInput.addEventListener('input', function() {
        if (!slugInput.value || slugInput.dataset.autoGenerated) {
            const slug = this.value
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-+|-+$/g, '');
            slugInput.value = slug;
            slugInput.dataset.autoGenerated = 'true';
        }
    });
    
    slugInput.addEventListener('input', function() {
        this.dataset.autoGenerated = '';
    });
});
</script>
@endpush