@extends('layouts.admin')

@section('title', 'Modifier un tag')
@section('page-title', 'Modifier le tag')
@section('page-description', 'Modification du tag : ' . $tag->name)

@section('content')
<div class="container-fluid">
    <form method="POST" action="{{ route('admin.tags.update', $tag) }}">
        @method('PUT')
        @include('admin.tags.partials.form', [
            'submitLabel' => 'Mettre A jour le tag',
            'tag' => $tag
        ])
    </form>
</div>
@endsection

@push('styles')
<style>






.bg-gradient-warning {
    background: linear-gradient(135deg, #f59e0b 0%, #10b981 100%);
}
</style>
@endpush

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Auto-generation du slug A partir du nom (mais pas en edition par defaut)
    const nameInput = document.getElementById('name');
    const slugInput = document.getElementById('slug');
    
    nameInput.addEventListener('input', function() {
        if (slugInput.dataset.autoGenerated) {
            const slug = this.value
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-+|-+$/g, '');
            slugInput.value = slug;
        }
    });
    
    slugInput.addEventListener('input', function() {
        this.dataset.autoGenerated = '';
    });
});
</script>
@endpush