@extends('layouts.admin')

@section('title', 'Creer une permission')
@section('page-title', 'Nouvelle permission')
@section('page-description', 'Creation d\'une nouvelle permission systeme')

@section('content')
<div class="container-fluid">
    <form method="POST" action="{{ route('admin.permissions.store') }}">
        @include('admin.permissions.partials.form', [
            'submitLabel' => 'Creer la permission'
        ])
    </form>
</div>
@endsection

@push('styles')
<style>






.bg-gradient-warning {
    background: linear-gradient(135deg, #f59e0b 0%, #10b981 100%);
}
</style>
@endpush

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Auto-generation du slug A partir du nom
    const nameInput = document.getElementById('name');
    const slugInput = document.getElementById('slug');
    const groupInput = document.getElementById('group');
    
    nameInput.addEventListener('input', function() {
        if (!slugInput.value || slugInput.dataset.autoGenerated) {
            const slug = this.value
                .toLowerCase()
                .replace(/\./g, '-')
                .replace(/[^a-z0-9-]+/g, '-')
                .replace(/^-+|-+$/g, '');
            slugInput.value = slug;
            slugInput.dataset.autoGenerated = 'true';
        }
        
        // Auto-remplir le groupe base sur le nom
        if ((!groupInput.value || groupInput.dataset.autoGenerated) && this.value.includes('.')) {
            const group = this.value.split('.')[0];
            groupInput.value = group;
            groupInput.dataset.autoGenerated = 'true';
        }
    });
    
    slugInput.addEventListener('input', function() {
        this.dataset.autoGenerated = '';
    });
    
    groupInput.addEventListener('input', function() {
        this.dataset.autoGenerated = '';
    });
});
</script>
@endpush