@extends('layouts.admin')

@section('title', 'Modifier une permission')
@section('page-title', 'Modifier la permission')
@section('page-description', 'Modification de la permission : ' . $permission->name)

@section('content')
<div class="container-fluid">
    <form method="POST" action="{{ route('admin.permissions.update', $permission) }}">
        @method('PUT')
        @include('admin.permissions.partials.form', [
            'submitLabel' => 'Mettre A jour la permission',
            'permission' => $permission
        ])
    </form>
</div>
@endsection

@push('styles')
<style>






.bg-gradient-warning {
    background: linear-gradient(135deg, #f59e0b 0%, #10b981 100%);
}
</style>
@endpush

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Auto-generation du slug (mais pas par defaut en edition)
    const nameInput = document.getElementById('name');
    const slugInput = document.getElementById('slug');
    const groupInput = document.getElementById('group');
    
    nameInput.addEventListener('input', function() {
        if (slugInput.dataset.autoGenerated) {
            const slug = this.value
                .toLowerCase()
                .replace(/\./g, '-')
                .replace(/[^a-z0-9-]+/g, '-')
                .replace(/^-+|-+$/g, '');
            slugInput.value = slug;
        }
        
        if (groupInput.dataset.autoGenerated && this.value.includes('.')) {
            const group = this.value.split('.')[0];
            groupInput.value = group;
        }
    });
    
    slugInput.addEventListener('input', function() {
        this.dataset.autoGenerated = '';
    });
    
    groupInput.addEventListener('input', function() {
        this.dataset.autoGenerated = '';
    });
});
</script>
@endpush